# Generated by Django 4.1.7 on 2023-04-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_remove_wishlist_wishlist_id_wishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlisttitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlisttitem',
            name='wishlist',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Wishlistt',
        ),
        migrations.DeleteModel(
            name='WishlisttItem',
        ),
    ]
