# Generated by Django 4.1.7 on 2023-03-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
