# Generated by Django 4.1.7 on 2023-03-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0003_useraddress_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'userAddress', 'verbose_name_plural': 'userAddresss'},
        ),
    ]
