# Generated by Django 4.1.7 on 2023-03-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_reviewrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_img', models.ImageField(upload_to='banner')),
                ('carousel_heading', models.CharField(max_length=200)),
                ('carousel_text', models.CharField(max_length=200)),
            ],
        ),
    ]
