# Generated by Django 4.1.7 on 2023-03-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_price_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='image',
            field=models.ImageField(blank=True, upload_to='productreview'),
        ),
    ]
