# Generated by Django 4.1.7 on 2023-03-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_variation_variation_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
    ]
