# Generated by Django 4.1.7 on 2023-03-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
