# Generated by Django 4.1.7 on 2023-03-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_image',
            field=models.ImageField(blank=True, default='profile/vk-high.png', null=True, upload_to='profile'),
        ),
    ]
